<a href="https://colab.research.google.com/github/myataqt/KuzmichLabs/blob/lab1/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_1_2_%D0%9C%D0%B0%D1%81%D1%81%D0%B8%D0%B2%D1%8B_%D0%B2_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Лабораторная работа № 1-2. Массивы в NumPY**

***В каждом задании выбираем задачу согласно номеру в списке***


*Подключите библиотеку NumPY*

In [ ]:
import numpy as np

**Задание 1.**
1.	Создайте массив из списка, состоящего из чисел от 0 до 9, при помощи функции array() из модуля numpy.
2.	Создайте массив из списка, состоящего из четных чисел от 0 до 20, при помощи функции array() из модуля numpy.
3.	Создайте массив из списка, состоящего из нечетных чисел от 0 до 20, при помощи функции array() из модуля numpy.
4.	Создайте массив из списка, состоящего из чисел кратных 3 от 20 до 30, при помощи функции array() из модуля numpy.
5.	Создайте массив из списка, состоящего из делителей числа 27, при помощи функции array() из модуля numpy.
6.	Создайте массив из списка, состоящего из делителей числа 16, при помощи функции array() из модуля numpy.
7.	Создайте массив из списка, состоящего из чисел кратных 5 от 1 до 50, при помощи функции array() из модуля numpy.
8.	Создайте массив из списка, состоящего из чисел кратных 4 от 20 до 60, при помощи функции array() из модуля numpy.
9.	Создайте массив из списка, состоящего из делителей числа 30, при помощи функции array() из модуля numpy.
10.	Создайте массив из списка, состоящего из делителей числа 64, при помощи функции array() из модуля numpy.
11.	Создайте массив из списка, состоящего из чисел от 30 до 40, при помощи функции array() из модуля numpy.
12.	Создайте массив из списка, состоящего из делителей числа 20, при помощи функции array() из модуля numpy.
13.	Создайте массив из списка, состоящего из делителей числа 50, при помощи функции array() из модуля numpy.
14.	Создайте массив из списка, состоящего из делителей числа 45, при помощи функции array() из модуля numpy.
15.	Создайте массив из списка, состоящего из делителей числа 12, при помощи функции array() из модуля numpy.
16.	Создайте массив из списка, состоящего из делителей числа 32, при помощи функции array() из модуля numpy.
17.	Создайте массив из списка, состоящего из делителей числа 81, при помощи функции array() из модуля numpy.
18.	Создайте массив из списка, состоящего из делителей числа 52, при помощи функции array() из модуля numpy.
19.	Создайте массив из списка, состоящего из чисел кратных 6 от 1 до 50, при помощи функции array() из модуля numpy.
20.	Создайте массив из списка, состоящего из чисел кратных 7 от 1 до 50, при помощи функции array() из модуля numpy.
21.	Создайте массив из списка, состоящего из чисел кратных 10 от 1 до 50, при помощи функции array() из модуля numpy.
22.	Создайте массив из списка, состоящего из чисел кратных 2 от 1 до 50, при помощи функции array() из модуля numpy.
23.	Создайте массив из списка, состоящего из чисел кратных 3 от 1 до 50, при помощи функции array() из модуля numpy.
24.	Создайте массив из списка, состоящего из чисел кратных 4 от 1 до 50, при помощи функции array() из модуля numpy.
25.	Создайте массив из списка, состоящего из чисел кратных 5 от 50 до 100, при помощи функции array() из модуля numpy.
26.	Создайте массив из списка, состоящего из чисел кратных 4 от 50 до 100, при помощи функции array() из модуля numpy.
27.	Создайте массив из списка, состоящего из чисел кратных 3 от 10 до 60, при помощи функции array() из модуля numpy.
28.	Создайте массив из списка, состоящего из чисел кратных 2 от 30 до 50, при помощи функции array() из модуля numpy.
29.	Создайте массив из списка, состоящего из чисел кратных 10 от 1 до 100, при помощи функции array() из модуля numpy.
30.	Создайте массив из списка, состоящего из чисел кратных 3 от 20 до 60, при помощи функции array() из модуля numpy.

In [ ]:
import math
def divisorgenerator(n):
    large_divisors = []
    for i in range(1, int(math.sqrt(n) + 1)):
        if n % i == 0:
            yield i
            if i * i != n:
                large_divisors.append(n / i)
    for divisor in reversed(large_divisors):
        yield divisor


divisors = list(divisorgenerator(50))
divisors_array = np.array(divisors)

print(divisors_array)

[ 1.  2.  5. 10. 25. 50.]


**Задание 2.**
1.	Создайте массив, состоящий из нечётных чисел от 1 до 19, при помощи функции arange() из модуля numpy.
2.	Создайте массив, состоящий из чётных чисел от 1 до 19, при помощи функции arange() из модуля numpy.
3.	Создайте массив, состоящий из нечётных чисел от 20 до 40, при помощи функции arange() из модуля numpy.
4.	Создайте массив, состоящий из чётных чисел от 30 до 60, при помощи функции arange() из модуля numpy.
5.	Создайте массив, состоящий из чисел кратных 3 в диапазоне от 100 до 200, при помощи функции arange() из модуля numpy.
6.	Создайте массив, состоящий из чисел кратных 4 в диапазоне от 100 до 200, при помощи функции arange() из модуля numpy.
7.	Создайте массив, состоящий из чисел кратных 5 в диапазоне от 100 до 200, при помощи функции arange() из модуля numpy.
8.	Создайте массив, состоящий из чисел кратных 6 в диапазоне от 100 до 200, при помощи функции arange() из модуля numpy.
9.	Создайте массив, состоящий из чисел кратных 7 в диапазоне от 100 до 200, при помощи функции arange() из модуля numpy.
10.	Создайте массив, состоящий из чисел кратных 8 в диапазоне от 100 до 200, при помощи функции arange() из модуля numpy.
11.	Создайте массив, состоящий из чисел кратных 9 в диапазоне от 100 до 200, при помощи функции arange() из модуля numpy.
12.	Создайте массив, состоящий из чисел кратных 10 в диапазоне от 100 до 200, при помощи функции arange() из модуля numpy.
13.	Создайте массив, состоящий из чисел кратных 3 в диапазоне от 1 до 100, при помощи функции arange() из модуля numpy.
14.	Создайте массив, состоящий из чисел кратных 4 в диапазоне от 1 до 100, при помощи функции arange() из модуля numpy.
15.	Создайте массив, состоящий из чисел кратных 5 в диапазоне от 1 до 100, при помощи функции arange() из модуля numpy.
16.	Создайте массив, состоящий из чисел кратных 6 в диапазоне от 1 до 100, при помощи функции arange() из модуля numpy.
17.	Создайте массив, состоящий из чисел кратных 7 в диапазоне от 1 до 100, при помощи функции arange() из модуля numpy.
18.	Создайте массив, состоящий из чисел кратных 8 в диапазоне от 1 до 100, при помощи функции arange() из модуля numpy.
19.	Создайте массив, состоящий из чисел кратных 9 в диапазоне от 1 до 100, при помощи функции arange() из модуля numpy.
20.	Создайте массив, состоящий из чисел кратных 10 в диапазоне от 1 до 100, при помощи функции arange() из модуля numpy.
21.	Создайте массив, состоящий из чисел кратных 3 в диапазоне от 200 до 300, при помощи функции arange() из модуля numpy.
22.	Создайте массив, состоящий из чисел кратных 4 в диапазоне от 200 до 300, при помощи функции arange() из модуля numpy.
23.	Создайте массив, состоящий из чисел кратных 5 в диапазоне от 200 до 300, при помощи функции arange() из модуля numpy.
24.	Создайте массив, состоящий из чисел кратных 6 в диапазоне от 200 до 300, при помощи функции arange() из модуля numpy.
25.	Создайте массив, состоящий из чисел кратных 7 в диапазоне от 200 до 300, при помощи функции arange() из модуля numpy.
26.	Создайте массив, состоящий из чисел кратных 8 в диапазоне от 200 до 300, при помощи функции arange() из модуля numpy.
27.	Создайте массив, состоящий из чисел кратных 9 в диапазоне от 200 до 300, при помощи функции arange() из модуля numpy.
28.	Создайте массив, состоящий из чисел кратных 10 в диапазоне от 200 до 300, при помощи функции arange() из модуля numpy.
29.	Создайте массив, состоящий из чисел кратных 25 в диапазоне от 200 до 300, при помощи функции arange() из модуля numpy.
30.	Создайте массив, состоящий из чисел кратных 11 в диапазоне от 200 до 300, при помощи функции arange() из модуля numpy.


In [ ]:
array = np.arange(3, 101, 3)

print(array)


[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


**Задание 3.** *Создайте массив, состоящий из a×b нулей (a – количество букв в имени, b – количество букв в фамилии). Затем сделайте из него двумерный массив размерности a×b. Выведите два массива.*

In [ ]:
a = 7 * 11
array_zeros = np.zeros((a))
print("Original Array:\n", array_zeros)

array_reshaped = np.reshape(array_zeros, (11, 7))
print("Reshaped Array:\n", array_reshaped)


Original Array:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0.]
Reshaped Array:
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**Задание 4.** *Создайте двумерный массив, состоящий из a×b единиц, в котором a строк и b столбцов (a – количество букв в имени, b – количество букв в фамилии).*

In [ ]:
array = np.ones((7, 11), dtype=int)

print(array)


[[1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1]]


**Задание 5.** *Создайте двумерный массив размерности a×b, состоящий из a×b равномерно распределённых чисел от 3 до 100 (a – количество букв в имени, b – количество букв в фамилии). Выведите тип элементов массива. Приведите массив к целому типу.*

In [ ]:
arr = np.linspace(3, 100, num=77).reshape(7, 11)

print(arr.dtype)

arr = arr.astype(int)

print(arr)

float64
[[  3   4   5   6   8   9  10  11  13  14  15]
 [ 17  18  19  20  22  23  24  25  27  28  29]
 [ 31  32  33  34  36  37  38  40  41  42  43]
 [ 45  46  47  48  50  51  52  54  55  56  57]
 [ 59  60  61  62  64  65  66  68  69  70  71]
 [ 73  74  75  77  78  79  80  82  83  84  85]
 [ 87  88  89  91  92  93  94  96  97  98 100]]
