<a href="https://colab.research.google.com/github/myataqt/KuzmichLabs/blob/lab3/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_5_6_%D0%98%D1%82%D0%BE%D0%B3%D0%BE%D0%B2%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_%D0%BF%D0%BE_NumPy_txt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## *Лабораторная работа* 5-6. Итоговая работа по NumPy

**Задание 1.** *Вычислите значения функции* $$f(x)=\log_{x^2+1}\dfrac{e^{5x+1}+\sqrt{x^5}+1}{|3\cos(2\pi x)+2\sin(x+\pi/12)|}$$
при $x=1, 10, 100.$

In [ ]:
import math

def compute_function(x):
  return math.log((math.e**(5*x + 1) + math.sqrt(x**5) + 1) / abs(3*math.cos(2*math.pi*x) + 2*math.sin(x+math.pi/12)), x**2 + 1)

print(compute_function(1))
print(compute_function(10))
print(compute_function(100))

**Задание 2** *Вычислите значения функции при изменении аргумента в некоторых приделах с заданным шагом.*

1) $f(x)=x^2$ на отрезке $[-2; 2]$ с шагом $0,01,$ с шагом $0,1,$ с шагом $0,25.$

2) $f(x)=\cos(2\pi t)$ на отрезке $[-10; 10]$ с шагом $0,25,$ с шагом $1.$

3) $f(x)=2\cos(t − 2) + \sin(2 t − 4)$ на отрезке $t\in [{}−20\pi; 10\pi]$ с шагом $\pi$ и с шагом $\dfrac{\pi}{12}\,.$

4) $f(x)=\log_2(|x|)$ на числовом множестве $[-4; 0)\cup (0; 4]$ с шагом $0,1,$ с шагом $0,25.$

5) $f(x)=\sqrt[5]{x}$ на отрезке $[1; 32]$ с шагом $1$ и с шагом $0.25.$

In [ ]:
import numpy as np

def f1(x):
    return x**2

for step in [0.01, 0.1, 0.25]:
    x_values = np.arange(-2, 2+step, step)
    y_values = f1(x_values)
    print(f"For step {step}, f(x) values are {y_values}")

def f2(t):
    return np.cos(2*np.pi*t)

for step in [0.25, 1]:
    t_values = np.arange(-10, 10+step, step)
    y_values = f2(t_values)
    print(f"For step {step}, f(x) values are {y_values}")

def f3(t):
    return 2*np.cos(t - 2) + np.sin(2*t - 4)

for step in [np.pi, np.pi/12]:
    t_values = np.arange(-20*np.pi, 10*np.pi+step, step)
    y_values = f3(t_values)
    print(f"For step {step}, f(x) values are {y_values}")

def f4(x):
    return np.log2(np.abs(x))

for step in [0.1, 0.25]:
    x_values = np.concatenate([np.arange(-4, 0, step), np.arange(step, 4+step, step)])
    y_values = f4(x_values)
    print(f"For step {step}, f(x) values are {y_values}")

def f5(x):
    return np.power(x, 1/5)

for step in [1, 0.25]:
    x_values = np.arange(1, 32+step, step)
    y_values = f5(x_values)
    print(f"For step {step}, f(x) values are {y_values}")


For step 0.01, f(x) values are [4.00000000e+00 3.96010000e+00 3.92040000e+00 3.88090000e+00
 3.84160000e+00 3.80250000e+00 3.76360000e+00 3.72490000e+00
 3.68640000e+00 3.64810000e+00 3.61000000e+00 3.57210000e+00
 3.53440000e+00 3.49690000e+00 3.45960000e+00 3.42250000e+00
 3.38560000e+00 3.34890000e+00 3.31240000e+00 3.27610000e+00
 3.24000000e+00 3.20410000e+00 3.16840000e+00 3.13290000e+00
 3.09760000e+00 3.06250000e+00 3.02760000e+00 2.99290000e+00
 2.95840000e+00 2.92410000e+00 2.89000000e+00 2.85610000e+00
 2.82240000e+00 2.78890000e+00 2.75560000e+00 2.72250000e+00
 2.68960000e+00 2.65690000e+00 2.62440000e+00 2.59210000e+00
 2.56000000e+00 2.52810000e+00 2.49640000e+00 2.46490000e+00
 2.43360000e+00 2.40250000e+00 2.37160000e+00 2.34090000e+00
 2.31040000e+00 2.28010000e+00 2.25000000e+00 2.22010000e+00
 2.19040000e+00 2.16090000e+00 2.13160000e+00 2.10250000e+00
 2.07360000e+00 2.04490000e+00 2.01640000e+00 1.98810000e+00
 1.96000000e+00 1.93210000e+00 1.90440000e+00 1.876900

**Задание 3.** *Создайте и выведите на экран массивы. Получившиеся матрицы сохраните в текстовые файлы.*

1) Из нулей создайте *одномерные* массивы длины 10 и 55, *двумерный* массив (матрицу) размера $3\times 4,$ *трехмерный* массив размера $2\times 4\times 5;$

2) Из единиц создайте *одномерные* массивы длины 10 и 55, *двумерный* массив (матрицу) размера $3\times 4,$ *трехмерный* массив размера $2\times 4\times 5;$

3) Из девяток создайте *одномерные* массивы длины 10 и 55, *двумерный* массив (матрицу) размера $3\times 4,$ *трехмерный* массив размера $2\times 4\times 5;$

4) Создайте *одномерные* массивы длины 10 и 55, *двумерный* массив (матрицу) размера $3\times 4,$ *трехмерный* массив размера $2\times 4\times 5,$ все элементы которых равны числу $0.25;$

5) Массив-диапазон от $-10$ до $10$ с шагом $0.1;$

6) Массив-диапазон от ${}-e$ до $e$ с шагом $\dfrac{e}{50}\,;$

7) Массив-диапазон от $-15\pi$ до $15\pi$ с шагом $\dfrac{\pi}{12}\,;$

8) Единичную матрицу размера $5\times 5;$

9) Диагональную матрицу размера $5\times 5,$ где все значения на главной диагонали равны $0.5;$

10) Матрицу размера $5\times 5,$ где на главной диагонали стоят единицы, а прочие элементы равны $2.$

11) Матрицу размера $5\times 5,$ где в первом столбце стоят единицы, во втором - двойки, в третьем - тройки и т.д.;

12) Матрицу размера $5\times 5,$ где в первой строке стоят единицы, во второй - двойки, в третьей - тройки и т.д.;

13) Матрицу размера $5\times 5,$ где на главной диагонали стоят нули, элементы выше нее - единицы, ниже - минус единицы;

14) Верхнюю треугольную матрицу размера $5 \times 5,$ где все элементы выше главной диагонали равны ${}−2,$ а на диагонали стоят единицы;

15) Нижнюю треугольную матрицу размера $5 \times 5,$ где все элементы ниже главной диагонали равны $2,$ а на диагонали стоят единицы.

In [ ]:
#task1
zeros_1d_10 = np.zeros(10)
zeros_1d_55 = np.zeros(55)
zeros_2d = np.zeros((3, 4))
zeros_3d = np.zeros((2, 4, 5))

print(zeros_1d_10)
print(zeros_1d_55)
print(zeros_2d)
print(zeros_3d)
np.savetxt('zeros_1d_10.txt', zeros_1d_10)
np.savetxt('zeros_1d_55.txt', zeros_1d_55)
np.savetxt('zeros_2d.txt', zeros_2d)
np.save('zeros_3d.npy', zeros_3d)

#task2
ones_1d_10 = np.ones(10)
ones_1d_55 = np.ones(55)
ones_2d = np.ones((3, 4))
ones_3d = np.ones((2, 4, 5))

print(ones_1d_10)
print(ones_1d_55)
print(ones_2d)
print(ones_3d)

np.savetxt('ones_1d_10.txt', ones_1d_10)
np.savetxt('ones_1d_55.txt', ones_1d_55)
np.savetxt('ones_2d.txt', ones_2d)
np.save('ones_3d.npy', ones_3d)

#task3
nines_1d_10 = np.full(10, 9)
nines_1d_55 = np.full(55, 9)
nines_2d = np.full((3, 4), 9)
nines_3d = np.full((2, 4, 5), 9)

print(nines_1d_10)
print(nines_1d_55)
print(nines_2d)
print(nines_3d)

np.savetxt('nines_1d_10.txt', nines_1d_10)
np.savetxt('nines_1d_55.txt', nines_1d_55)
np.savetxt('nines_2d.txt', nines_2d)
np.save('nines_3d.npy', nines_3d)

#task4
point25_1d_10 = np.full(10, 0.25)
point25_1d_55 = np.full(55, 0.25)
point25_2d = np.full((3, 4), 0.25)
point25_3d = np.full((2, 4, 5), 0.25)

print(point25_1d_10)
print(point25_1d_55)
print(point25_2d)
print(point25_3d)

np.savetxt('point25_1d_10.txt', point25_1d_10)
np.savetxt('point25_1d_55.txt', point25_1d_55)
np.savetxt('point25_2d.txt', point25_2d)
np.save('point25_3d.npy', point25_3d)

#task5
range_01 = np.arange(-10, 10.1, 0.1)

print(range_01)

np.savetxt('range_01.txt', range_01)

#task6
range_e = np.arange(-np.e, np.e+np.e/50, np.e/50)

print(range_e)

np.savetxt('range_e.txt', range_e)

#task7
range_pi = np.arange(-15*np.pi, 15*np.pi+(np.pi/12), np.pi/12)

print(range_pi)

np.savetxt('range_pi.txt', range_pi)

#task8
unit_matrix = np.eye(5)

print(unit_matrix)

np.savetxt('unit_matrix.txt', unit_matrix)

#task9
diag_matrix = np.full((5, 5), 0.5) * np.eye(5)

print(diag_matrix)

np.savetxt('diag_matrix.txt', diag_matrix)

#task10
ones_diag_matrix = np.full((5, 5), 2) - np.eye(5)

print(ones_diag_matrix)

np.savetxt('ones_diag_matrix.txt', ones_diag_matrix)

#task11
col_matrix = np.tile(np.arange(1, 6), (5, 1))

print(col_matrix)

np.savetxt('col_matrix.txt', col_matrix)

#task12
row_matrix = np.tile(np.arange(1, 6), (5, 1)).T

print(row_matrix)

np.savetxt('row_matrix.txt', row_matrix)

#task13
diag_zero_matrix = np.triu(np.ones((5, 5)), 1) + np.tril(-1*np.ones((5, 5)), -1)

print(diag_zero_matrix)

np.savetxt('diag_zero_matrix.txt', diag_zero_matrix)

#task14
upper_tri_matrix = np.triu(-2*np.ones((5, 5)), 1) + np.eye(5)

print(upper_tri_matrix)

np.savetxt('upper_tri_matrix.txt', upper_tri_matrix)

#task15
lower_tri_matrix = np.tril(2*np.ones((5, 5)), -1) + np.eye(5)

print(lower_tri_matrix)

np.savetxt('lower_tri_matrix.txt', lower_tri_matrix)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[9 9 9 9 9 9 9 9 9 9]
[9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9
 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
[[[9 9 9 9 9]
  [9 9 9 9 

**Задание 4.** *Решите системы линейных уравнений* $\,A^2X=B\,$ *и* $\,A^3A^{T}A^2X=B,\,$ *если*
$$
A=\left(\!
\begin{array}{cccc}
2 & 4 & 7 & 4 \\
4 & 1 & 6 & 2 \\
8 & 3 & 6 & 7 \\
6 & 3 & 5 & 7
\end{array}\!\right),
\qquad
B = \left(
\begin{array}{c}
2 \\
0 \\
3 \\
1
\end{array}\right).
$$

In [ ]:
A = np.array([[2, 4, 7, 4], [4, 1, 6, 2], [8, 3, 6, 7], [6, 3, 5, 7]])
B = np.array([2, 0, 3, 1])

A2 = np.dot(A, A)

X1 = np.linalg.solve(A2, B)

print("Solution to the system A^2X = B is", X1)

A3AT_A2 = np.dot(np.dot(A, A), np.dot(A, A.T))

X2 = np.linalg.solve(A3AT_A2, B)

print("Solution to the system A^3A^TA^2X = B is", X2)


Solution to the system A^2X = B is [ 0.078 -0.256  0.764 -0.76 ]
Solution to the system A^3A^TA^2X = B is [ 1.260281 -1.996096  4.329189 -4.684465]


**Задание 5.** *Дан массив из* $\ N\leq 30\ $ *случайных целых чисел. Вычислите:*

* сумму элементов массива;
* минимальный и максимальный элементы массива;
* среднее квадратичное чисел массива;
* элемент массива, наиболее удаленный от среднего арифметического чисел массива.

In [ ]:
import numpy as np

np.random.seed(0)
arr = np.random.randint(1, 100, 30)

sum_arr = np.sum(arr)
print("Sum of the array elements: ", sum_arr)

min_arr = np.min(arr)
max_arr = np.max(arr)
print("Minimum element of the array: ", min_arr)
print("Maximum element of the array: ", max_arr)

mean_square_arr = np.mean(arr**2)
print("Mean square of the array numbers: ", mean_square_arr)

mean_arr = np.mean(arr)

diff_arr = np.abs(arr - mean_arr)

farthest_element = arr[np.argmax(diff_arr)]
print("Element farthest from the arithmetic mean: ", farthest_element)


Sum of the array elements:  1745
Minimum element of the array:  10
Maximum element of the array:  89
Mean square of the array numbers:  4052.5666666666666
Element farthest from the arithmetic mean:  10
