<a href="https://colab.research.google.com/github/myataqt/KuzmichLabs/blob/lab2/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_3_4_%D0%9E%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B8_%D0%BD%D0%B0%D0%B4_%D0%BC%D0%B0%D1%81%D1%81%D0%B8%D0%B2%D0%B0%D0%BC%D0%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Лабораторная работа № 3-4. Операции над массивами

***В каждом задании выбираем задачу согласно номеру в списке***



*Подключите библиотеку NumPY*

In [ ]:
import numpy as np

**Задание 1.** *Используя соответствующие функции вычислите значение функции f(x) в 100 равномерно распределенных точках отрезка [a, b].*
<table>
   <tr>
    <th>№ варианта</th>
    <th>f(x)</th>
    <th>a</th>
    <th>b</th>
   </tr>
   <tr><td>1</td><td>$$\sin x$$</td><td>$$-\pi$$</td><td>$$\pi$$</td></tr>
   <tr><td>2</td><td>$$\cos x$$</td><td>$$-\pi$$</td><td>$$\pi$$</td></tr>
   <tr><td>3</td><td>$$\tan x$$</td><td>$$-\pi$$</td><td>$$\pi$$</td></tr>
   <tr><td>4</td><td>$$\arcsin x$$</td><td>-1</td><td>1</td></tr>
   <tr><td>5</td><td>$$\arccos x$$</td><td>-1</td><td>1</td></tr>
   <tr><td>6</td><td>$$\arctan x$$</td><td>-5</td><td>5</td></tr>
   <tr><td>7</td><td>$$x^2$$</td><td>-3</td><td>3</td></tr>
   <tr><td>8</td><td>$$\ln x$$</td><td>1</td><td>20</td></tr>
   <tr><td>9</td><td>$$\lg x$$</td><td>1</td><td>30</td></tr>
   <tr><td>10</td><td>$$\log[2] x$$</td><td>1</td><td>40</td></tr>
   <tr><td>11</td><td>$$\sqrt{x}$$</td><td>0</td><td>40</td></tr>
   <tr><td>12</td><td>$$\sqrt[3]{x}$$</td><td>-20</td><td>20</td></tr>
   <tr><td>13</td><td>$$|x|$$</td><td>-6</td><td>6</td></tr>
   <tr><td>14</td><td>$$e^x$$</td><td>-30</td><td>30</td></tr>
   <tr><td>15</td><td>$$x^3$$</td><td>-5</td><td>10</td></tr>
   <tr><td>16</td><td>$$\sqrt[4]{x}$$</td><td>0</td><td>25</td></tr>
   <tr><td>17</td><td>$$\sin x^2$$</td><td>$$-\pi$$</td><td>$$\pi$$</td></tr>
   <tr><td>18</td><td>$$\cos x^2$$</td><td>$$-\pi$$</td><td>$$\pi$$</td></tr>
   <tr><td>19</td><td>$$\tan x^2$$</td><td>$$-\pi$$</td><td>$$\pi$$</td></tr>
   <tr><td>20</td><td>$$\lg^2 x$$</td><td>1</td><td>20</td></tr>
   <tr><td>21</td><td>$$\arcsin x^2$$</td><td>-1</td><td>1</td></tr>
   <tr><td>22</td><td>$$\arccos x^2$$</td><td>-1</td><td>1</td></tr>
   <tr><td>23</td><td>$$\arctan x^2$$</td><td>-6</td><td>6</td></tr>
   <tr><td>24</td><td>$$\ln x^2$$</td><td>-5</td><td>5</td></tr>
   <tr><td>25</td><td>$$\lg x^2$$</td><td>-6</td><td>6</td></tr>
   <tr><td>26</td><td>$$\log[2]{x^2}$$</td><td>-8</td><td>8</td></tr>   
   <tr><td>27</td><td>$$\ln^2 x$$</td><td>1</td><td>10</td></tr>
   <tr><td>28</td><td>$$\log_2^2 x$$</td><td>2</td><td>50</td></tr>
   <tr><td>29</td><td>$$\sqrt[3]{x^2}$$</td><td>-20</td><td>20</td></tr>
   <tr><td>30</td><td>$$\sin^2 x$$</td><td>$$-\pi$$</td><td>$$\pi$$</td></tr>
  </table>

In [ ]:
x = np.linspace(-6, 6, 100)

y = np.abs(x)

for i in range(len(x)):
    print("x: ", x[i], " y: ", y[i])

x:  -6.0  y:  6.0
x:  -5.878787878787879  y:  5.878787878787879
x:  -5.757575757575758  y:  5.757575757575758
x:  -5.636363636363637  y:  5.636363636363637
x:  -5.515151515151516  y:  5.515151515151516
x:  -5.393939393939394  y:  5.393939393939394
x:  -5.2727272727272725  y:  5.2727272727272725
x:  -5.151515151515151  y:  5.151515151515151
x:  -5.03030303030303  y:  5.03030303030303
x:  -4.909090909090909  y:  4.909090909090909
x:  -4.787878787878788  y:  4.787878787878788
x:  -4.666666666666666  y:  4.666666666666666
x:  -4.545454545454545  y:  4.545454545454545
x:  -4.424242424242424  y:  4.424242424242424
x:  -4.303030303030303  y:  4.303030303030303
x:  -4.181818181818182  y:  4.181818181818182
x:  -4.0606060606060606  y:  4.0606060606060606
x:  -3.9393939393939394  y:  3.9393939393939394
x:  -3.8181818181818183  y:  3.8181818181818183
x:  -3.696969696969697  y:  3.696969696969697
x:  -3.5757575757575757  y:  3.5757575757575757
x:  -3.4545454545454546  y:  3.4545454545454546
x:  -3

**Задание 2.** *Создайте два целочисленных одномерных массива размерности a*b (a- количество букв в имени, b – количество букв в фамилии). Найдите поэлементную сумму массивов, поэлементную разность массивов, остаток от деления элементов первого массива на второй, произведение соответствующих элементов массивов.*


In [ ]:
array1 = np.random.randint(100, size=77)
array2 = np.random.randint(100, size=77)

sum_array = array1 + array2

diff_array = array1 - array2

remainder_array = np.mod(array1, array2)

product_array = array1 * array2

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nSum of Arrays:")
print(sum_array)
print("\nDifference of Arrays:")
print(diff_array)
print("\nRemainder of Division:")
print(remainder_array)
print("\nProduct of Arrays:")
print(product_array)

Array 1:
[33 38  3  7  8 13 51 52 38 93 49 45 33 22 12 79 58 52 91 71  7 12 42 82
 49 67 84 66 78 46 86 16 76 57 55 39 62 51 84 80 14 76 11 43 66 60 91 72
 62 25 99 99 81 87 42 77 49 84 59 81 85 17 34 73 50 32 84 83 57 29 57 55
 78 63 22 42 32]

Array 2:
[ 2 38 39 80 75 59 97 70 70 65 43 31 45 24 30 38  7 70 76 60 61 83 75 68
 83 95 26 36 25 17 41 47 51 37 21 24 90 70 49 52 28 36 78  4 15 37  9 36
 58  4 19 37 81 56 30 51 64 32 30 42 26 25 57 78 43 49 80 53 63 69 99 79
 74 57  9 39 67]

Sum of Arrays:
[ 35  76  42  87  83  72 148 122 108 158  92  76  78  46  42 117  65 122
 167 131  68  95 117 150 132 162 110 102 103  63 127  63 127  94  76  63
 152 121 133 132  42 112  89  47  81  97 100 108 120  29 118 136 162 143
  72 128 113 116  89 123 111  42  91 151  93  81 164 136 120  98 156 134
 152 120  31  81  99]

Difference of Arrays:
[ 31   0 -36 -73 -67 -46 -46 -18 -32  28   6  14 -12  -2 -18  41  51 -18
  15  11 -54 -71 -33  14 -34 -28  58  30  53  29  45 -31  25  20  34  15
 -28 -19  

**Задание 3.** *Для одного из массивов, созданных в предыдущем задании найдите сумму всех элементов, среднее значение, дисперсию и среднеквадратичное отклонение. Выведите наибольший и наименьший элемент массива и их индексы.*

In [ ]:
sum_array1 = np.sum(array1)
print("Sum of Array 1:", sum_array1)

mean_array1 = np.mean(array1)
print("Mean of Array 1:", mean_array1)

var_array1 = np.var(array1)
print("Variance of Array 1:", var_array1)

std_array1 = np.std(array1)
print("Standard Deviation of Array 1:", std_array1)

max_element = np.max(array1)
max_index = np.argmax(array1)
print("Largest Element of Array 1:", max_element, "at index", max_index)

min_element = np.min(array1)
min_index = np.argmin(array1)
print("Smallest Element of Array 1:", min_element, "at index", min_index)


Sum of Array 1: 4158
Mean of Array 1: 54.0
Variance of Array 1: 671.2207792207793
Standard Deviation of Array 1: 25.907928887133746
Largest Element of Array 1: 99 at index 50
Smallest Element of Array 1: 3 at index 2


**Задание 4.** *Проверьте есть ли в созданных в задании 2 массивах элементы из массива [2,5,8,10].*

In [ ]:
values_to_check = np.array([2,5,8,10])

contains_values_sum = np.isin(sum_array, values_to_check)
print("Does sum_array contain elements from values_to_check?", np.any(contains_values_sum))

contains_values_diff = np.isin(diff_array, values_to_check)
print("Does diff_array contain elements from values_to_check?", np.any(contains_values_diff))

contains_values_product = np.isin(product_array, values_to_check)
print("Does product_array contain elements from values_to_check?", np.any(contains_values_product))

contains_values_remainder = np.isin(remainder_array, values_to_check)
print("Does remainder_array contain elements from values_to_check?", np.any(contains_values_remainder))


Does sum_array contain elements from values_to_check? False
Does diff_array contain elements from values_to_check? False
Does product_array contain elements from values_to_check? False
Does remainder_array contain elements from values_to_check? True


**Задание 5.** *Создайте двумерный массив размерности a*b (a- количество букв в имени, b – количество букв в фамилии) с помощью срезов вывести элементы, стоящие в первой строке, второй строке, первом столбце, втором столбце, в первой и второй строке и третьем и четвертом столбце, в последней строке, в последнем столбце, в двух последних строках и двух последних строках*

In [ ]:
arr = np.arange(77).reshape(7, 11)

print(" ")
# First row
print(arr[0, :])

# Second row
print(arr[1, :])

# First column
print(arr[:, 0])

# Second column
print(arr[:, 1])

# First and second row and third and fourth column
print(arr[0:2, 2:4])

# Last row
print(arr[-1, :])

# Last column
print(arr[:, -1])

# Last two rows
print(arr[-2:, :])

# Last two rows and third and fourth column
print(arr[-2:, 2:4])


[ 0  1  2  3  4  5  6  7  8  9 10]
----------------------------------------------------------------------
[11 12 13 14 15 16 17 18 19 20 21]
----------------------------------------------------------------------
[ 0 11 22 33 44 55 66]
----------------------------------------------------------------------
[ 1 12 23 34 45 56 67]
----------------------------------------------------------------------
[[ 2  3]
 [13 14]]
----------------------------------------------------------------------
[66 67 68 69 70 71 72 73 74 75 76]
----------------------------------------------------------------------
[10 21 32 43 54 65 76]
----------------------------------------------------------------------
[[55 56 57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76]]
----------------------------------------------------------------------
[[57 58]
 [68 69]]
----------------------------------------------------------------------
